name: publish

on: [push]

jobs:
  publish-on-github:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build . --tag ghcr.io/LordMrcS/nginx-php-fpm:latest
        docker run ghcr.io/LordMrcS/nginx-php-fpm:latest
        docker push ghcr.io/LordMrcS/nginx-php-fpm:latest