name: Publish image to Github Image Registry
on:
  # Runs on pushes targeting the default branch
  push:
    paths-ignore:
     - ".github/**"
     - "**.md"
  pull_request:
    paths-ignore:
     - ".github/**"
     - "**.md"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set branch-based environment variables
      uses: iamtheyammer/branch-env-vars@v1.2.0
      with:
        TAG: |
          master:latest
          php81:php81
          php74:php74
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${{ secrets.DOCKER_USERNAME }}/nginx-php-fpm-ldap
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: ${{ env.TAG }}
